// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/design-system": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/design-system";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/design-system.tsx": {
    id: "routes/design-system";
    page: "/design-system";
  };
};

type RouteModules = {
  "root": typeof import("./src/root.tsx");
  "routes/_index": typeof import("./src/routes/_index.tsx");
  "routes/design-system": typeof import("./src/routes/design-system.tsx");
};