import type { ChargeOverview, EnergyOverview } from "@grid-platform/contracts";

export const energyOverview: EnergyOverview = {
  mode: "mock",
  generatedAt: "Mock snapshot · no live device connection",
  sites: [
    {
      id: "site-verna",
      name: "Verna Works",
      location: "Goa",
      status: "healthy",
      freshness: "live",
      solarKw: 126.4,
      loadKw: 91.2,
      batterySoc: 78,
      gridKw: -21.4,
      openAlerts: 0,
    },
    {
      id: "site-porvorim",
      name: "Porvorim Residence",
      location: "Goa",
      status: "warning",
      freshness: "stale",
      solarKw: 8.2,
      loadKw: 5.7,
      batterySoc: 31,
      gridKw: 1.4,
      openAlerts: 1,
    },
    {
      id: "site-pune",
      name: "Pune Logistics",
      location: "Maharashtra",
      status: "offline",
      freshness: "unconfirmed",
      solarKw: 0,
      loadKw: 0,
      batterySoc: 0,
      gridKw: 0,
      openAlerts: 2,
    },
  ],
  leads: [
    {
      id: "lead-1042",
      customer: "Aster Hospitality",
      siteType: "Resort",
      stage: "Survey scheduled",
      owner: "Meera",
      nextAction: "Site visit · 14 Jul",
    },
    {
      id: "lead-1041",
      customer: "Konkan Cold Chain",
      siteType: "Industrial",
      stage: "Proposal in progress",
      owner: "Arjun",
      nextAction: "Confirm load profile",
    },
    {
      id: "lead-1038",
      customer: "Dona Paula Homes",
      siteType: "Residential",
      stage: "Negotiation",
      owner: "Meera",
      nextAction: "Review assumptions",
    },
  ],
};
export const chargeOverview: ChargeOverview = {
  mode: "mock",
  generatedAt: "Mock snapshot · no live charger connection",
  chargers: [
    {
      id: "chg-pnj-01",
      name: "Panaji Hub · A",
      city: "Panaji",
      status: "charging",
      connectors: 2,
      activeSessions: 1,
      freshness: "live",
    },
    {
      id: "chg-mrg-02",
      name: "Margao Central",
      city: "Margao",
      status: "available",
      connectors: 4,
      activeSessions: 0,
      freshness: "live",
    },
    {
      id: "chg-vrn-03",
      name: "Verna Works",
      city: "Verna",
      status: "faulted",
      connectors: 2,
      activeSessions: 0,
      freshness: "stale",
    },
  ],
};
